---

- include: node.yml

- name: Create blog user for Ghost
  sudo: yes
  user: >
    name={{ blog_user }}
    comment=Ghost
    home={{ blog_user_home }}
    shell=/bin/bash

- name: Download Ghost
  sudo: yes
  get_url: >
    url={{ ghost_zip_url }}
    dest={{ blog_user_home }}/ghost.zip
    owner={{ blog_user }} group={{ blog_user }}
  notify: run ghost

- name: Expand Ghost
  sudo: yes
  shell: >
    sudo unzip {{ blog_user_home }}/ghost.zip -d {{ blog_user_home }}/ghost
    chdir={{ blog_user_home }}
    creates={{ blog_user_home }}/ghost

- name: Copy Ghost config
  sudo: yes
  template: >
    src=ghost-config.j2
    dest={{ blog_user_home }}/ghost/config.js
    owner={{ blog_user }} group={{ blog_user }}
  notify: run ghost

- name: Install Ghost dependencies
  sudo: yes
  npm: >
    path={{ blog_user_home }}/ghost
    production=yes
  notify: run ghost

- name: Change directory owner
  sudo: yes
  file: >
    path={{ blog_user_home }}/ghost
    owner={{ blog_user }} group={{ blog_user }}
    state=directory recurse=yes

- name: Install Ghost service
  sudo: yes
  template: >
    src=ghost-service.j2
    dest=/etc/init/ghost.conf
    owner=root group=root mode=644
  notify: run ghost

- name: Copy Ghost nginx config
  sudo: yes
  template: >
    src=ghost-nginx.j2
    dest=/etc/nginx/sites-available/ghost
    owner=root group=root mode=644
  notify: restart nginx

- name: Make site available in nginx
  sudo: yes
  file: >
    src=/etc/nginx/sites-available/ghost
    dest=/etc/nginx/sites-enabled/ghost
    owner=root group=root state=link
  notify: restart nginx
